### ISSUE TITLE
Breasts vibrate rapidly if using timeline.

### ISSUE THREAD

**Issue by Jatts-Art** [Vaaskr/KK_StudioBustAdjuster#2]
As the title says. First time using this in the timeline and yeah it just vibrates to an extreme level if I use any of this plugin's interpolates, no idea why.

**Comment by Jatts-Art** [comment]
Just to add onto what I've posted the other day, here is a recorded clip that better explains what is going on. Placed the clip inside of dropdown text, due to nudity.

<details><summary>Video Clip</summary>

https://github.com/Vaaskr/StudioBustAdjuster/assets/12752293/cc2949a7-016e-4122-ac2b-0dd0fae4d206

</details>

**Comment by Vaaskr** [comment]
> Just to add onto what I've posted the other day, here is a recorded clip that better explains what is going on. Placed the clip inside of dropdown text, due to nudity.
> 
> Video Clip

I'm actually unsure of what would be causing that kind of issue with the timeline interpolates. The only thing I can think of it being would be plugin compatibility. It seems to be a physics issue, I see that you are using VNGE, which has a physics module so that may be causing issues. I don't use VNGE personally but if you can try to disable the plugin and see if it has any affect just let me know if anything changes.

**Comment by Jatts-Art** [comment]
Sorry for the delay, but alrighty I'll test VNGE and other plugins and I'll see what's causing this. I had a feeling it may likely be plugin compatibility as well.

**Comment by Vaaskr** [comment]
> Sorry for the delay, but alrighty I'll test VNGE and other plugins and I'll see what's causing this. I had a feeling it may likely be plugin compatibility as well.

I have a hunch that it might be VNGE but not sure. if its VNGE I'll see what I can do to make a patch.

**Comment by Jatts-Art** [comment]
Interesting... so actually no, it is not VNGE. I removed it entirely, temporarily, and the vibrating still exists. I will continue testing other plugins.

**Comment by Jatts-Art** [comment]
Just as a quick, blind, shot in the dark... I removed a large chunk of plugins and yet the vibration still continues. Here's a screencap of what I took out of my folder to test. Not sure what else it could possibly be at this point, hmm..

![7a3bbd18740f2d2d500603202aefb522](https://github.com/Vaaskr/StudioBustAdjuster/assets/12752293/a3d4d856-811c-4332-b172-4f0fc25e0724)

**Comment by Vaaskr** [comment]
Quick Question, are you using KKmanger and the latest version of the HF patch?

**Comment by Jatts-Art** [comment]
I'm using latest version of KK Manager, however I've not updated with HF Patch specifically recently. I always keep pretty much all plugins updated manually and very often check their posts on the KK server.

Here is another screencap of my other plugins, in case theres something else of interest to be seen:
![41d0e10a67aadcee032eeeb9d684d1ad](https://github.com/Vaaskr/StudioBustAdjuster/assets/12752293/b8044c5c-8563-4bf1-ae24-2c95fe31a3bd)

**Comment by Vaaskr** [comment]
What is the latest versions of KKAPI, KKAMBX and Pushup do you have?

**Comment by Jatts-Art** [comment]
KKAPI v1.4
KKAMBX v5.2
Pushup v1.4

**Comment by Vaaskr** [comment]
I'm out of date with HF Patch so I'm going to update and see if it breaks the plugin, ill get back to ya.

**Comment by Vaaskr** [comment]
> I'm out of date with HF Patch so I'm going to update and see if it breaks the plugin, ill get back to ya.

with everything up to date and i could not replicate your issue. The only thing i can think of is mod incompatibility with any mod may have added not included in the HF patch or a bad download of StudioBustAdjuster.

**Comment by Jatts-Art** [comment]
I will check with a few friends of mine to see if they have the issue as well, since we often share the same mods and plugins DLs with eachother.

**Comment by Jatts-Art** [comment]
So I returned to this and did some thinking, and thought about how its possibly relating to a plugin and yet removing plugins isnt helping out... therefore I concluded that perhaps it relates to a plugin's _settings_ rather than a plugin simply being installed. To test this, I temporarily cleared my entire config folder and I tested in-game... and it worked, no more twitching!

So, now I need to narrow it down and find the specific plugin setting that is causing this. Will post those results soon enough.

**Comment by Jatts-Art** [comment]
Okay, the cause of vibration has finally been found. It is a specific ABMX edit on a specific bust bone. It would seem that if editing the Offset of "cf_d_bust03_L/R", it causes the vibrations to occur for timeline.

![Vibration True](https://github.com/Vaaskr/StudioBustAdjuster/assets/12752293/9e00bed8-729e-4675-a20b-7c1da32e4a91)

![Vibration False](https://github.com/Vaaskr/StudioBustAdjuster/assets/12752293/f1218183-7047-485a-9b92-a9f5a06a9069)

This leads to another issue... recently I've just released a large pack of body templates and a number of them have this specific bone edited: <https://www.pixiv.net/en/artworks/119261833>

So, if this is at all possible to fix then that'd be great! Otherwise I'd have to go back and edit that bone for all of these, lol... as well as any other WIP cards with this same edit.

**Comment by Vaaskr** [comment]
I went and tested it on one of my characters and its not just cf_d_bust03 its any bust bone that has a modified offset that starts with cf_d_bust. I don't know if I can fix the issue without breaking the plugin. what's causing issue is that my plugin uses pushup to recalculate the body every time the sliders in the Current state menu are changed as shown in the screenshot below. ![Screenshot 2024-06-03 165426](https://github.com/Vaaskr/StudioBustAdjuster/assets/38697288/1bfd4a11-b445-43d7-bc9d-fecd7df7234b)
The timeline section calls upon the same function to make it change, causing it to recalculate every frame which normally works fine, unless the bones have been offset. if I were to remove that highlighted section then it would not change the way the bust looks. I usually don't offset any bust bone as it can causes issues even without my plugin, but if you need to try using any bone that starts with cf_s_bust, that didn't seem to vibrate when offset.

**Comment by Jatts-Art** [comment]
I decided to go and change some of those cards that needed it since they needed other tweaks anyway. Thanks again for the help!
